# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(731, 340)
        MainWindow.setStyleSheet("background-color:rgb(255, 255, 255)")
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Logo = QtWidgets.QLabel(self.centralwidget)
        self.Logo.setGeometry(QtCore.QRect(38, 40, 350, 250))
        self.Logo.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Logo.setText("")
        self.Logo.setPixmap(QtGui.QPixmap(":/img/resources/YTTDL-LOGO.png"))
        self.Logo.setObjectName("Logo")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(440, 60, 261, 201))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Label_welcome = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.Label_welcome.setFont(font)
        self.Label_welcome.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_welcome.setObjectName("Label_welcome")
        self.verticalLayout.addWidget(self.Label_welcome)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.Lineedit_URL = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.Lineedit_URL.setFont(font)
        self.Lineedit_URL.setStyleSheet("QLineEdit\n"
"{\n"
"    border:2px groove gray;\n"
"    border-radius:5px;\n"
"}\n"
"QLineEdit:hover\n"
"{\n"
"    background-color: #e7e7e7;\n"
"}\n"
"")
        self.Lineedit_URL.setObjectName("Lineedit_URL")
        self.verticalLayout.addWidget(self.Lineedit_URL)
        spacerItem1 = QtWidgets.QSpacerItem(20, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.pushButton_dl = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.pushButton_dl.setFont(font)
        self.pushButton_dl.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_dl.setWhatsThis("")
        self.pushButton_dl.setStyleSheet("QPushButton\n"
"{\n"
"    border:2px groove gray;\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    background-color: #e7e7e7;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(152, 152, 152);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}")
        self.pushButton_dl.setFlat(False)
        self.pushButton_dl.setObjectName("pushButton_dl")
        self.verticalLayout.addWidget(self.pushButton_dl)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "YouTube Thumbnail Downloader"))
        MainWindow.setToolTip(_translate("MainWindow", "<html><head/><body><p>Paste your YouTube video link here, e.g. <a href=\"https://www.youtube.com/watch?v=dQw4w9WgXcQ\"><span style=\" text-decoration: underline; color:#0000ff;\">https://www.youtube.com/watch?v=dQw4w9WgXcQ</span></a></p></body></html>"))
        self.Logo.setToolTip(_translate("MainWindow", "<html><head/><body><p>YouTube Thumbnail Downloader</p></body></html>"))
        self.Logo.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.Label_welcome.setText(_translate("MainWindow", "Welcome"))
        self.Lineedit_URL.setToolTip(_translate("MainWindow", "<html><head/><body><p>Paste your YouTube video link here, e.g. <a href=\"https://www.youtube.com/watch?v=dQw4w9WgXcQ\"><span style=\" text-decoration: underline; color:#0000ff;\">https://www.youtube.com/watch?v=dQw4w9WgXcQ</span></a></p></body></html>"))
        self.Lineedit_URL.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.Lineedit_URL.setPlaceholderText(_translate("MainWindow", "Paste your YouTube video link here"))
        self.pushButton_dl.setToolTip(_translate("MainWindow", "<html><head/><body><p>Click to download the thumbnail</p></body></html>"))
        self.pushButton_dl.setText(_translate("MainWindow", "Download"))
import resources_rc
